
import React from 'react'

import { ScrollView,StyleSheet, View , Text  } from 'react-native'
 
export default function PolicyScreen() {

    return (

        <ScrollView>

            <View style={styles.private}>

                <Text style={styles.privateInside}> Private Policy</Text>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>1.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature.</Text>

                </View>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>2.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms of use for access or usage of the domain name (“Website”) and the corresponding application.</Text>

                </View>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>3.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}>By accessing the Website or Application, whether through a mobile device, mobile application or computer, the User agrees to be bound by the Terms of Use ('Terms') and this Privacy Policy ('Policy') whether or not the User creates an account to avail of the Service. If the User wishes to avail of the Service, the User does hereby unequivocally accept and agree to the contents of the Terms and Policy.

                       </Text>

                </View>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>4.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}>The Application has been designed by the Company to assist the User in connecting with other Users of the application, in providing technical accessibility between the Users, and creating a common platform wherein transactions between the Users are carried out in a seamless and efficient manner, using various third party products/services to be decided at the discretion of the Company, to be added to the Application from time to time, including but not limited to third party payment gateways ("Service").

                    </Text>

                </View>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>5.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}>The use of the Website and Application by the User is solely governed by these Terms read with the Privacy Policy and any modifications or amendments made thereto by the Company from time to time, at its sole discretion. Accessing the Application and/or using any of the information or Services provided therein shall be deemed to signify the User's unequivocal acceptance of these Terms and the aforementioned Policy, and the User expressly agrees to be bound by the same, regardless of however the User or anyone on the User's behalf has accessed, installed, downloaded or used the Application. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either one will lead to the termination of the other. The User may not access the Application or avail of any of the Services provided by the Company if the User does not accept and agree to be bound by the Terms and Policy. In the event that the User or anyone acting on the User's behalf does not wish to be bound by the Terms and the Policy, the User (or the legal person/entity acting on the User's behalf) unequivocally agrees to refrain from accessing, using or retaining the Application on any device in any manner whatsoever. The User agrees that anything done or caused to be done by the User or anyone acting on the User's behalf, whether expressly or impliedly in contravention with the Terms or Policy, will render the User liable for legal and punitive action.

                    </Text>

                </View>

            </View>

            <View style={styles.rules} >

                <View>

                    <Text style={styles.rulesInsider}>6.</Text>

                </View>

                <View>

                    <Text style={styles.rulesInside}>DIVULGING/SHARING OF PERSONAL INFORMATION

                        The User is aware that the Application/Company may share the User's personal information with other entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Application's services; and to facilitate joint or co-branded services, where such services are provided by more than one entity.

                        The User is aware that the Application/Company may disclose personal information if required to do so by law or if the Application/Company in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The Application/Company may also disclose the User's personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.

                    </Text>

                </View>

            </View>

        </ScrollView>

    )

}
 
const styles = StyleSheet.create({

    private: {

        paddingTop: 40,

        paddingLeft: 20,

        paddingRight: 20,

    },

    privateInside: {

        fontWeight: "600",

        fontSize: 24,

        color: 'red'

    },

    rules: {

        paddingLeft: 20,

        paddingRight: 20,

        paddingTop: 10,

        flexDirection: 'row',

        width:380

    },

    rulesInside: {

        fontWeight: "400",

        fontSize: 16,

    },

    rulesInsider: {

        fontWeight: "600",

        fontSize: 16,

    }

})

 